const express=require("express")
const mongoose=require("mongoose")
const path = require("path")
const render=require("./controller/render")
const register=require("./controller/register")
const test=require("./controller/test")
const api=require("./controller/api")
const app=express()
require("dotenv").config()
app.use(express.json())
app.use(express.static(path.join(__dirname,"./public"),{index:false}))
mongoose.connect(process.env.STRING)
.then(()=>{
    console.log("connected to db sucessfully")
}).catch(err=>{
    console.log(err)
})
app.get("/",render)
app.get("/api",api)
app.get("/test",test)
app.post("/",register)
app.listen(5000,()=>{
    console.log("Listening to port 5000")
})